export const itineraryImageMap: Record<string, string[]> = {
  AE: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AE/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AE/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AE/3.jpg",
  ],
  AR: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AR/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AR/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AR/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AR/4.jpg",
  ],
  AT: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AT/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AT/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AT/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AT/4.jpg",
  ],
  AU: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AU/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AU/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/AU/3.jpg",
  ],
  BE: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BE/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BE/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BE/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BE/4.jpg",
  ],
  BG: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BG/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BG/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BG/3.jpg",
  ],
  BR: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BR/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BR/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BR/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/BR/4.jpg",
  ],
  CA: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CA/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CA/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CA/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CA/4.jpg",
  ],
  CH: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CH/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CH/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CH/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CH/4.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CH/5.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CH/6.jpg",
  ],
  CL: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CL/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CL/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CL/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CL/4.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CL/5.jpg",
  ],
  CN: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CN/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CN/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CN/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CN/4.jpg",
  ],
  CZ: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CZ/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CZ/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CZ/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/CZ/4.jpg",
  ],
  DE: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/DE/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/DE/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/DE/3.jpg",
  ],
  EG: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/EG/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/EG/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/EG/3.jpg",
  ],
  ES: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ES/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ES/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ES/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ES/4.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ES/5.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ES/6.jpg",
  ],
  FI: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/FI/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/FI/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/FI/3.jpg",
  ],
  FR: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/FR/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/FR/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/FR/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/FR/4.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/FR/5.jpg",
  ],
  GB: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/GB/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/GB/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/GB/3.jpg",
  ],
  GR: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/GR/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/GR/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/GR/3.jpg",
  ],
  HR: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/HR/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/HR/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/HR/3.jpg",
  ],
  HU: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/HU/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/HU/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/HU/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/HU/4.jpg",
  ],
  ID: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ID/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ID/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ID/3.jpg",
  ],
  IE: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IE/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IE/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IE/3.jpg",
  ],
  IL: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IL/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IL/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IL/3.jpg",
  ],
  IN: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IN/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IN/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IN/3.jpg",
  ],
  IS: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IS/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IS/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IS/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IS/4.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IS/5.jpg",
  ],
  IT: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IT/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IT/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IT/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IT/4.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IT/5.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/IT/6.jpg",
  ],
  JO: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/JO/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/JO/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/JO/3.jpg",
  ],
  JP: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/JP/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/JP/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/JP/3.jpg",
  ],
  KE: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KE/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KE/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KE/3.jpg",
  ],
  KH: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KH/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KH/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KH/3.jpg",
  ],
  KR: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KR/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KR/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KR/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/KR/4.jpg",
  ],
  LA: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/LA/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/LA/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/LA/3.jpg",
  ],
  LK: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/LK/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/LK/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/LK/3.jpg",
  ],
  MA: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MA/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MA/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MA/3.jpg",
  ],
  MM: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MM/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MM/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MM/3.jpg",
  ],
  MV: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MV/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MV/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MV/3.jpg",
  ],
  MX: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MX/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MX/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MX/3.jpg",
  ],
  MY: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MY/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MY/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MY/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/MY/4.jpg",
  ],
  NA: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NA/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NA/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NA/3.jpg",
  ],
  NL: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NL/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NL/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NL/3.jpg",
  ],
  NO: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NO/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NO/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NO/3.jpg",
  ],
  NP: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NP/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NP/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NP/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NP/4.jpg",
  ],
  NZ: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NZ/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NZ/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NZ/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/NZ/4.jpg",
  ],
  PE: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PE/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PE/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PE/3.jpg",
  ],
  PH: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PH/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PH/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PH/3.jpg",
  ],
  PL: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PL/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PL/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PL/3.jpg",
  ],
  PT: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PT/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PT/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PT/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PT/4.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/PT/5.jpg",
  ],
  RO: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/RO/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/RO/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/RO/3.jpg",
  ],
  SA: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SA/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SA/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SA/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SA/4.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SA/5.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SA/6.jpg",
  ],
  SE: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SE/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SE/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SE/3.jpg",
  ],
  SG: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SG/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SG/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SG/3.jpg",
  ],
  SI: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SI/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SI/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SI/3.jpg",
  ],
  SK: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SK/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SK/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/SK/3.jpg",
  ],
  TH: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/TH/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/TH/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/TH/3.jpg",
  ],
  TR: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/TR/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/TR/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/TR/3.jpg",
  ],
  TZ: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/TZ/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/TZ/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/TZ/3.jpg",
  ],
  US: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/US/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/US/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/US/3.jpg",
  ],
  VN: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/VN/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/VN/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/VN/3.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/VN/4.jpg",
  ],
  ZA: [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ZA/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ZA/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/ZA/3.jpg",
  ],

  // THEMES
  "_themes/USA-road-trip": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/USA-road-trip/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/USA-road-trip/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/USA-road-trip/3.jpg",
  ],
  "_themes/adventure-and-outdoors": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/adventure-and-outdoors/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/adventure-and-outdoors/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/adventure-and-outdoors/3.jpg",
  ],
  "_themes/african-safari": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/african-safari/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/african-safari/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/african-safari/3.jpg",
  ],
  "_themes/alpine-scenic-route": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/alpine-scenic-route/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/alpine-scenic-route/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/alpine-scenic-route/3.jpg",
  ],
  "_themes/caribbean-islands": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/caribbean-islands/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/caribbean-islands/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/caribbean-islands/3.jpg",
  ],
  "_themes/central-europe": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/central-europe/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/central-europe/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/central-europe/3.jpg",
  ],
  "_themes/european-christmas-markets": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/european-christmas-markets/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/european-christmas-markets/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/european-christmas-markets/3.jpg",
  ],
  "_themes/greek-islands": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/greek-islands/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/greek-islands/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/greek-islands/3.jpg",
  ],
  "_themes/himalayas": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/himalayas/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/himalayas/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/himalayas/3.jpg",
  ],
  "_themes/japan-cherry-blossom": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/japan-cherry-blossom/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/japan-cherry-blossom/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/japan-cherry-blossom/3.jpg",
  ],
  "_themes/mediterranean-summer": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/mediterranean-summer/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/mediterranean-summer/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/mediterranean-summer/3.jpg",
  ],
  "_themes/middle-east-luxury": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/middle-east-luxury/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/middle-east-luxury/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/middle-east-luxury/3.jpg",
  ],
  "_themes/northern-lights": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/northern-lights/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/northern-lights/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/northern-lights/3.jpg",
  ],
  "_themes/patagonia": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/patagonia/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/patagonia/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/patagonia/3.jpg",
  ],
  "_themes/romantic-europe": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/romantic-europe/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/romantic-europe/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/romantic-europe/3.jpg",
  ],
  "_themes/scandinavia": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/scandinavia/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/scandinavia/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/scandinavia/3.jpg",
  ],
  "_themes/south-east-asia": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/south-east-asia/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/south-east-asia/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_themes/south-east-asia/3.jpg",
  ],

  // DEFAULT (see note below)
  "_default": [
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_default1/1.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_default1/2.jpg",
    "https://hegvp3kaqm660g9n.public.blob.vercel-storage.com/_default1/3.jpg",
  ],
};
